#!/usr/bin/env php
<?php
declare(strict_types = 1);

$paths = [
    __DIR__.'/vendor/autoload.php',
    __DIR__ . '/../../../vendor/autoload.php',
];

foreach ($paths as $file) {
    if (file_exists($file)) {
        require $file;

        break;
    }
}

use Innmind\CLI\{
    Main,
    Environment,
};
use Innmind\Url\Path;
use Innmind\OperatingSystem\OperatingSystem;
use function Innmind\Tower\bootstrap;

new class extends Main {
    protected function main(Environment $env, OperatingSystem $os): void
    {
        $path = new Path(
            $env->variables()['TOWER_CONFIG'] ?? $env->workingDirectory().'/tower.yml'
        );

        $run = bootstrap(
            $os->control(),
            $os->remote(),
            $os->ports(),
            $path
        );
        $run($env);
    }
};
