#!/usr/bin/env php
<?php
declare(strict_types = 1);

$paths = [
    __DIR__.'/vendor/autoload.php',
    __DIR__ . '/../../../vendor/autoload.php',
];

foreach ($paths as $file) {
    if (file_exists($file)) {
        require $file;

        break;
    }
}

use Innmind\CLI\Framework\{
    Main,
    Application,
};
use Innmind\Url\Path;
use function Innmind\Tower\bootstrap;

new class extends Main {
    protected function configure(Application $app): Application
    {
        return $app->commands(static function($env, $os) {
            $path = $env->workingDirectory()->resolve(Path::of('tower.yml'));

            if ($env->variables()->contains('TOWER_CONFIG')) {
                $path = Path::of($env->variables()->get('TOWER_CONFIG'));
            }

            return bootstrap(
                $os->control(),
                $os->remote(),
                $os->ports(),
                $os->sockets(),
                $path,
            );
        });
    }
};
