arguments:
    configPath: Innmind\Url\PathInterface

expose:
    commands: $commands

services:
    commands Innmind\CLI\Commands:
        - $command.trigger
        - $command.ping
        - $command.listen

    command:
        trigger Innmind\Tower\Command\Trigger:
            - $run
        ping Innmind\Tower\Command\Ping:
            - $configuration
            - $ping
        listen Innmind\Tower\Command\Listen:
            - $server
            - $loop

    configuration Innmind\Tower\Configuration::load:
        - $configPath
        - $loader

    loader Innmind\Tower\Configuration\Yaml: []

    ping Innmind\Tower\Ping\Delegate:
        - $ping.map

    ping:
        map map<string, Innmind\Tower\Ping>:
            - <tcp, $ping.tcp>
            - <ssh, $ping.ssh>

        tcp Innmind\Tower\Ping\Tcp: []
        ssh Innmind\Tower\Ping\Ssh:
            - $server

    server Innmind\Server\Control\ServerFactory::build: []

    run Innmind\Tower\Run:
        - $server
        - $configuration
        - $ping

    loop Innmind\Socket\Loop:
        - $eventBus
        - $timeout

    eventBus Innmind\EventBus\EventBus:
        - $listeners

    listeners map<string, Innmind\Immutable\SetInterface>:
        - <Innmind\Socket\Event\DataReceived, $listeners.data>
    listeners:
        data set<callable>:
            - $listeners.data.run
        data:
            run Innmind\Tower\Listener\Ping:
                - $run

    timeout Innmind\TimeContinuum\ElapsedPeriod:
        - 3600000 # one hour
